# Generated by Django 3.2.9 on 2021-11-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='applicant',
            name='reg_date',
            field=models.DateField(),
        ),
    ]
